# From https://github.com/koalaman/shellcheck/wiki/TravisCI
language: bash

# Use container-based infrastructure for quicker build start-up
sudo: false

before_install:
  - go get -u github.com/mvdan/sh/cmd/shfmt

addons:
  apt:
    sources:
    - debian-sid    # Grab shellcheck from the Debian repo (o_O)
    packages:
    - shellcheck

script:
 - make check

matrix:
  fast_finish: true
