language: go  # Use go language for shfmt
go:
  - master

# Use container-based infrastructure for quicker build start-up
sudo: false

addons:
  apt:
    sources:
    - debian-sid    # Grab shellcheck from the Debian repo (o_O)
    packages:
    - shellcheck

env:
  - GOPATH=~/.go

install:
  - go get -u github.com/mvdan/sh/cmd/shfmt

script:
 - make check

matrix:
  fast_finish: true
